name: Full Store
favicon: null
layout_spectrum: 0.33224101713858545
typography_spectrum: 0.9377598857972771
title: Tienda Online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcff00'
    - '#000000'
    - '#ff009c'
    - '#ffffff'
    - '#6b6c00'
  brandStrength: 0.7701390227302909
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.43697349540889263
purpose: []
